import type { Metadata } from "next";
import { Inter, Jost } from "next/font/google";
import dynamic from 'next/dynamic';
// import Header from "../components/main-header/MainHeader"
import Footer from "../components/main-footer/Mainfooter"
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const jost = Jost({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const Header = dynamic(() => import('../components/main-header/MainHeader'), { ssr: false });
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">

      <body className={jost.className}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}



// 'use client'
// import type { Metadata } from "next";
// import { Inter, Jost } from "next/font/google";
// import { useState } from "react";
// import { useRouter } from "next/router";
// import Header from "../components/main-header/MainHeader"
// import Footer from "../components/main-footer/Mainfooter"
// import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });
// const jost = Jost({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {

//   const [activeComponent, setActiveComponent] = useState(children);
//   const router = useRouter();

//   const handleLinkClick = (component: React.ReactNode) => {
//     setActiveComponent(component);
//     router.push("#"); // Optional: scroll to top or update URL
//   };
//   return (
//     <html lang="en">

//       <body className={jost.className}>
//         {/* <Header /> */}
//         <Header onLinkClick={handleLinkClick} />
//         {activeComponent}
//         {/* {children} */}
//         <Footer />
//       </body>
//     </html>
//   );
// }
